<a href="https://colab.research.google.com/github/Meryemsahin0/Python/blob/main/Hi_kod6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
""" Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.
 İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.
 Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. """

In [ ]:
import numpy as np

my_array=np.array([13,19,1187,1948,1517,2024],dtype=int)
print(type(my_array))
print(my_array.shape)
print(len(my_array))

<class 'numpy.ndarray'>
(6,)
6


In [ ]:
array1=np.array([[1,2,3],[4,5,6],[5,8,9]])
print(type(array1))
print(array1.shape)
print(len(array1))
print()

<class 'numpy.ndarray'>
(3, 3)
3


In [1]:
import numpy as np


arr1d = np.array([1, 2, 3, 4, 5])
print(f"1 boyutlu array: {arr1d}")
print(f"1 boyutlu array'den eleman alma: {arr1d[2]}")
print(f"1 boyutlu array'den dilim alma: {arr1d[1:4]}")


arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n2 boyutlu array: {arr2d}")
print(f"2 boyutlu array'den eleman alma: {arr2d[1, 2]}")
print(f"2 boyutlu array'den dilim alma: {arr2d[1:, 0:2]}")


arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"\n3 boyutlu array: {arr3d}")
print(f"3 boyutlu array'den eleman alma: {arr3d[1, 0, 1]}")
print(f"3 boyutlu array'den dilim alma: {arr3d[:, 1, :]}")

1 boyutlu array: [1 2 3 4 5]
1 boyutlu array'den eleman alma: 3
1 boyutlu array'den dilim alma: [2 3 4]

2 boyutlu array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
2 boyutlu array'den eleman alma: 6
2 boyutlu array'den dilim alma: [[4 5]
 [7 8]]

3 boyutlu array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3 boyutlu array'den eleman alma: 6
3 boyutlu array'den dilim alma: [[3 4]
 [7 8]]
